---
- name: Apagar diretorios testar systemd
  shell: cd /lib/systemd/system/sysinit.target.wants/ && rm -rf /lib/systemd/system/anaconda.target.wants/* && rm -f /lib/systemd/system/basic.target.wants/ && rm -f /lib/systemd/system/sockets.target.wants/initctl && rm -f /lib/systemd/system/local-fs.target.wants/ && rm -f /lib/systemd/system/sockets.target.wants/udev && rm -f /etc/systemd/system/.wants/

- name: Run systemctl --user
  command: systemctl --user
