---
- name: Install epel
  yum:
    name: epel-release
    state: installed

- name: install nginx
  yum:
    name: nginx
    state: installed

- name: Enable Nginx
  systemd:
    name: nginx
    enabled: true
  notify:
    - Daemon reload
    - Start nginx
