---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: nginx
    image: centos/systemd:latest
    command: /usr/sbin/init
    environment:
      container: docker
    privileged: true
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    env:
      XDG_RUNTIME_DIR: "/run/user/$UID"
      DBUS_SESSION_BUS_ADDRESS: "unix:path=${XDG_RUNTIME_DIR}/bus"
provisioner:
  name: ansible
  v: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
